# Generated by Django 5.1.4 on 2024-12-24 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('-date_joined',)},
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='cause',
            new_name='reason',
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
